name: "Build + Push"

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]
    branches: [main]

jobs:
  on-success:
    name: publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Building APK
        run: ./gradlew assembleDebug

      - name: Upload to Firebase App Distribution
        run: ./gradlew appDistributionUploadDebug