name: "Build + Push"

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]
    branches: [main]

jobs:
  on-success:
    name: publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Building and sharing APK
        env:
          KEYSTORE_CONTENT: ${{ secrets.KEYSTORE_CONTENT }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          SERVICE_CREDENTIALS_JSON: ${{ secrets.SERVICE_CREDENTIALS_JSON }}
        run: |
          chmod +x setup-env.sh
          source ./setup-env.sh
          export SERVICE_CREDENTIALS_PATH="$(pwd)/firebase.json"
          export KEYSTORE_PATH="$(pwd)/keystore.jks"
          ./gradlew check -x detekt
          ./gradlew appDistributionUploadDebug